version = 0.1
[y]
[y.deploy]
[y.deploy.parameters]
stack_name = "dynamodb-streamsStack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1vtrfmzfyzkou"
s3_prefix = "dynamodb-streamsStack"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dynamodb-streamStack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1vtrfmzfyzkou"
s3_prefix = "dynamodb-streamStack"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
